// app/layout.tsx
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { Noto_Sans_JP } from 'next/font/google'; // ★ フォントをインポート

// ★ フォントをインスタンス化
const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'], // 'japanese' も利用可能です
  weight: ['300', '400'], // 必要なウェイト
  display: 'swap',
});

export const metadata = {
  title: 'Next Market',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    // ★ フォントクラスを<html>に適用
    <html lang="ja" className={notoSansJp.className}>
      {/* ★ <body>にベーススタイルを適用 (max-w, mx-auto, px, font-weight, color) */}
      <body className="font-light text-[#333] max-w-[1100px] mx-auto px-[15px]">
        <Header />
        {/* ★ <main>にデフォルトのテキストスタイルを適用 
          (font-size: 18px, line-height: 35px)
        */}
        <main className="text-lg leading-[35px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;