// app/layout.tsx
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata = {
  title: 'Next Market',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body>
        {/* divのラッパーは不要 */}
        <Header />
        <main> {/* 特別なクラスは不要 */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;